### ISSUE TITLE
Fake issue for ORCA ICG failures

### ISSUE THREAD

**Issue by l-wang** [greenplum-db/gpdb-postgres-merge#41]
### teach ORCA translator about invalid constraints:
- [x] alter_table

### flakes?
- [ ] instr_in_shmem_verify

### super slow query with ORCA
- [x] subselect

### mac sorts differently from linux?
- [ ] decode_expr

### stale ORCA expect files:
- [x] union
- [x] rangefuncs
- [x] function_extensions
- [x] update_gp
- [x] table_functions
- [x] co_nestloop_idxscan
- [x] subselect_gp
- [x] partition_locking (we're not sure though)
- [x] portals_updatable
- [x] bfv_dd
- [x] bb_mpph
- [x] qp_correlated_query
- [x] gporca
- [x] bfv_index
- [x] olap_window_seq
- [x] bfv_subquery

### CTE
- [x] qp_misc_jiras
- [x] qp_derived_table
- [x] qp_olap_window
- [x] qp_with_clause
- [x] with_clause

### no clue
- [x] gpctas
- [x] sreh
- [x] bfv_partition
- [x] qp_dropped_cols
- [ ] query_info_hook_test
- [x] bfv_aggregate
- [x] inherit

### crashing sadly
- [x] qp_targeted_dispatch
- [x] qp_functions
- [x] qp_correlated_query
- [x] qp_misc_rio_join_small
- [x] qp_misc_rio
- [x] qp_gist_indexes2
- [x] qp_gist_indexes3
- [x] qp_gist_indexes4
- [x] qp_query_execution
- [x] dpe                   
- [x] qp_dpe                
- [x] qp_subquery           
- [x] qp_left_anti_semi_join
- [x] qp_union_intersect    
- [x] qp_functions_idf      
- [x] qp_regexp             
- [x] qp_resource_queue     
- [x] qp_orca_fallback

**Comment by paul-guo-** [comment]
iteration_9 was finished. Closing.
